export const foodSeeds = [
  // --- Original 10 items (updated with foodRestrictions) ---
  {
    name: 'Frango Grelhado',
    caloriesPer100g: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    foodRestrictions: ['Celíaco', 'Colesterol alto'],
  },
  {
    name: 'Arroz Branco Cozido',
    caloriesPer100g: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Sem restrições'],
  },
  {
    name: 'Banana',
    caloriesPer100g: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Sem restrições'],
  },
  {
    name: 'Ovo (inteiro cozido)',
    caloriesPer100g: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    foodRestrictions: ['Vegetariano', 'Celíaco'],
  },
  {
    name: 'Leite Integral',
    caloriesPer100g: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    foodRestrictions: ['Vegetariano'],
  },
  {
    name: 'Pão Integral',
    caloriesPer100g: 265,
    protein: 9,
    carbs: 49,
    fat: 3.3,
    foodRestrictions: ['Vegetariano'],
  },
  {
    name: 'Abóbora Cozida',
    caloriesPer100g: 22,
    protein: 0.8,
    carbs: 5,
    fat: 0.1,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Salmão Grelhado',
    caloriesPer100g: 208,
    protein: 22,
    carbs: 0,
    fat: 13,
    foodRestrictions: ['Celíaco', 'Colesterol alto'],
  },
  {
    name: 'Maçã',
    caloriesPer100g: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Sem restrições'],
  },
  {
    name: 'Batata Doce Cozida',
    caloriesPer100g: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },

  // --- Fruits (8 new items) ---
  {
    name: 'Laranja',
    caloriesPer100g: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Morango',
    caloriesPer100g: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Manga',
    caloriesPer100g: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Uva',
    caloriesPer100g: 69,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Abacaxi',
    caloriesPer100g: 50,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Pera',
    caloriesPer100g: 57,
    protein: 0.4,
    carbs: 15,
    fat: 0.1,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Melancia',
    caloriesPer100g: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Kiwi',
    caloriesPer100g: 61,
    protein: 1.1,
    carbs: 15,
    fat: 0.5,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },

  // --- Vegetables (8 new items) ---
  {
    name: 'Brócolis',
    caloriesPer100g: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Cenoura',
    caloriesPer100g: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Espinafre',
    caloriesPer100g: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Tomate',
    caloriesPer100g: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Alface',
    caloriesPer100g: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Pepino',
    caloriesPer100g: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Beterraba',
    caloriesPer100g: 43,
    protein: 1.6,
    carbs: 10,
    fat: 0.2,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Couve',
    caloriesPer100g: 49,
    protein: 4.3,
    carbs: 9,
    fat: 0.9,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  // --- Grains (5 new items) ---
  {
    name: 'Aveia',
    caloriesPer100g: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
    foodRestrictions: ['Vegano', 'Vegetariano'],
  },
  {
    name: 'Macarrão Cozido',
    caloriesPer100g: 158,
    protein: 5.8,
    carbs: 31,
    fat: 0.9,
    foodRestrictions: ['Vegano', 'Vegetariano'],
  },
  {
    name: 'Quinoa Cozida',
    caloriesPer100g: 120,
    protein: 4.4,
    carbs: 22,
    fat: 1.9,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Milho Cozido',
    caloriesPer100g: 96,
    protein: 3.4,
    carbs: 21,
    fat: 1.5,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Pão de Forma Branco',
    caloriesPer100g: 265,
    protein: 8,
    carbs: 51,
    fat: 3.2,
    foodRestrictions: ['Vegetariano'],
  },

  // --- Legumes (4 new items) ---
  {
    name: 'Feijão Preto Cozido',
    caloriesPer100g: 132,
    protein: 8.9,
    carbs: 24,
    fat: 0.5,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Lentilha Cozida',
    caloriesPer100g: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Grão-de-Bico Cozido',
    caloriesPer100g: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },
  {
    name: 'Ervilha Cozida',
    caloriesPer100g: 84,
    protein: 5.4,
    carbs: 15,
    fat: 0.4,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },

  // --- Dairy (3 new items) ---
  {
    name: 'Iogurte Natural',
    caloriesPer100g: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    foodRestrictions: ['Vegetariano'],
  },
  {
    name: 'Queijo Mussarela',
    caloriesPer100g: 280,
    protein: 22,
    carbs: 2.2,
    fat: 22,
    foodRestrictions: ['Vegetariano'],
  },
  {
    name: 'Requeijão',
    caloriesPer100g: 255,
    protein: 7.5,
    carbs: 3.5,
    fat: 24,
    foodRestrictions: ['Vegetariano'],
  },

  // --- Meats/Poultry (3 new items) ---
  {
    name: 'Carne Bovina Magra',
    caloriesPer100g: 218,
    protein: 26,
    carbs: 0,
    fat: 12,
    foodRestrictions: ['Celíaco', 'Colesterol alto'],
  },
  {
    name: 'Peito de Peru',
    caloriesPer100g: 135,
    protein: 29,
    carbs: 0,
    fat: 1.7,
    foodRestrictions: ['Celíaco', 'Colesterol alto'],
  },
  {
    name: 'Atum em Lata (água)',
    caloriesPer100g: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
    foodRestrictions: ['Celíaco', 'Colesterol alto'],
  },

  // --- Fish (2 new items) ---
  {
    name: 'Tilápia Grelhada',
    caloriesPer100g: 128,
    protein: 26,
    carbs: 0,
    fat: 2.7,
    foodRestrictions: ['Celíaco', 'Colesterol alto'],
  },
  {
    name: 'Sardinha em Lata',
    caloriesPer100g: 208,
    protein: 25,
    carbs: 0,
    fat: 11,
    foodRestrictions: ['Celíaco', 'Colesterol alto'],
  },

  // --- Eggs/Other (2 new items) ---
  {
    name: 'Clara de Ovo',
    caloriesPer100g: 52,
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
    foodRestrictions: ['Vegetariano', 'Celíaco', 'Colesterol alto'],
  },
  {
    name: 'Tofu',
    caloriesPer100g: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco', 'Colesterol alto', 'Sem restrições'],
  },

  // --- Prepared/Other (5 new items) ---
  {
    name: 'Maionese',
    caloriesPer100g: 680,
    protein: 1,
    carbs: 0.6,
    fat: 75,
    foodRestrictions: ['Vegetariano'],
  },
  {
    name: 'Azeite de Oliva',
    caloriesPer100g: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco'],
  },
  {
    name: 'Manteiga',
    caloriesPer100g: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    foodRestrictions: ['Vegetariano'],
  },
  {
    name: 'Mel',
    caloriesPer100g: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    foodRestrictions: ['Vegetariano', 'Celíaco', 'Colesterol alto'],
  },
  {
    name: 'Amendoim Torrado',
    caloriesPer100g: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    foodRestrictions: ['Vegano', 'Vegetariano', 'Celíaco'],
  },
];
